<?php

namespace Almo\WalletBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Almo\WalletBundle\AlmoWalletBundle;

/**
 * UsersRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function findAllOperationsByLoginId($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT o, u
				FROM AlmoWalletBundle:Operations o join o.user_id u
				WHERE u.id = :id')
            ->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
