<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{

    public function getUserAccountsStatus(\App\Entity\User $user)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT a, p, sum(p.amount) as total FROM App\Entity\Payment p
							JOIN p.accountId a
							JOIN p.currencyId c
							WHERE a.userId = :userId
							group by c.id, a.id")
            ->setParameter('userId', $user->getId());

        return $query->getResult();
    }

    public function getUserAccountPaymentsQuery($accountId, \App\Entity\User $user)
    {
        $query = $this->getAllUserPaymentsQueryBuilder($user)
            ->andWhere('p.accountId = :accountId')
            ->setParameter('accountId', $accountId)
            ->getQuery();

        return $query;
    }

    public function getAllUserPaymentsQueryBuilder(\App\Entity\User $user)
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('App\Entity\Payment', 'p')
            ->join('p.accountId', 'a')
            ->join('p.operationId', 'o')
            ->where('a.userId = :userId')
            ->orderBy('o.date', 'DESC')
            ->setParameter('userId', $user->getId());

        return $qb;
    }

    public function getUserPaymentsTagsQuery(\App\Entity\User $user)
    {
        $query = $this->getAllUserPaymentsQueryBuilder($user)
            ->groupBy('o.tagId')
            ->getQuery();

        return $query;
    }

    public function findAllOrderByDate()
    {
        return $this->getEntityManager()
            ->createQuery('Select p from Operations p order by p.date desc')
            ->getResult();
    }
}
