<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{

    public function getUserTags(\App\Entity\Users $User, $type)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT t FROM App\Entity\Tags t
							WHERE t.userId = :userId and t.payType = :type")
            ->setParameter('userId', $User->getId())
            ->setParameter('type', $type);

        return $query->getResult();
    }

    public function findAllOrderByDate()
    {
        return $this->getEntityManager()
            ->createQuery('Select p from Operations p order by p.date desc')
            ->getResult();
    }
}
