<?php

namespace Almo\WalletBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentsRepository extends EntityRepository
{
    public function getUserAccountsStatus(\Almo\UserBundle\Entity\Users $User)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT a, p, sum(p.amount) as total FROM Almo\WalletBundle\Entity\Payments p
							JOIN p.accountId a
							JOIN p.currencyId c
							WHERE a.userId = :userId
							group by c.id, a.id")
            ->setParameter('userId', $User->getId());

        return $query->getResult();
    }

    public function getUserAccountPayments($accountId, \Almo\UserBundle\Entity\Users $User)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT p FROM Almo\WalletBundle\Entity\Payments p
							JOIN p.accountId a
							JOIN p.operationId o
							WHERE a.userId = :userId and p.accountId = :accountId
							ORDER BY o.date DESC")
            ->setParameter('userId', $User->getId())
            ->setParameter('accountId', $accountId);

        return $query->getResult();
    }

    public function findAllOrderByDate()
    {
        return $this->getEntityManager()
            ->createQuery('Select p from AlmoWalletBundle:Operations p order by p.date desc')
            ->getResult();
    }
}
