<?php

namespace Almo\WalletBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentsRepository extends EntityRepository
{
    public function getUserAccountsStatus(\Almo\UserBundle\Entity\Users $User)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT a, p, sum(p.amount) as total FROM Almo\WalletBundle\Entity\Payments p
							JOIN p.accountId a
							JOIN p.currencyId c
							WHERE a.userId = :userId
							group by c.id, a.id")
            ->setParameter('userId', $User->getId());

        return $query->getResult();
    }

    public function getUserAccountPaymentsQuery($accountId, \Almo\UserBundle\Entity\Users $user)
    {
        $query = $this->getAllUserPaymentsQueryBuilder($user)
            ->andWhere('p.accountId = :accountId')
            ->setParameter('accountId', $accountId)
            ->getQuery();

        return $query;
    }

    public function getAllUserPaymentsQueryBuilder(\Almo\UserBundle\Entity\Users $user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('p')->from('Almo\WalletBundle\Entity\Payments', 'p')
            ->join('p.accountId', 'a')
            ->join('p.operationId', 'o')
            ->where('a.userId = :userId')
            ->orderBy('o.date',  'DESC')
            ->setParameter('userId', $user->getId());

        return $qb;
    }

    public function getUserPaymentsTagsQuery(\Almo\UserBundle\Entity\Users $user)
    {
        $query = $this->getAllUserPaymentsQueryBuilder($user)
            ->groupBy('o.tagId')->getQuery();

        return $query;
    }

    public function findAllOrderByDate()
    {
        return $this->getEntityManager()
            ->createQuery('Select p from AlmoWalletBundle:Operations p order by p.date desc')
            ->getResult();
    }
}
